# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VCjJl_QKO1hRaMLwQpO4wDutZ7mK_1K
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import joblib

# 1. Load dataset
df = pd.read_csv("/content/data/dataset_dummy.csv")

# 2. Pisahkan fitur dan label
X = df.drop(columns=["jurusan"])
y = df["jurusan"]

# 3. Split data (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. Latih model Random Forest
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 5. Prediksi & evaluasi
y_pred = model.predict(X_test)
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

# 7. Simpan model dan fitur
joblib.dump(model, "/content/data/model_ansaju.pkl")
joblib.dump(list(X.columns), "/content/data/fitur_model.pkl")
print("Model dan fitur berhasil disimpan.")